using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AD.Api.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class EnumToStringGenerator : IIncrementalGenerator
{
	private const string ATTRIBUTE_FULL_NAME = "AD.Api.Generators.GenerateEnumToStringAttribute";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// 1) Inject the attribute into the user's compilation (so they don't need a shared "Abstractions" project).
		context.RegisterPostInitializationOutput(static ctx =>
		{
			ctx.AddSource(
				"GenerateEnumToStringAttribute.g.cs",
				SourceText.From(ATTRIBUTE_SOURCE, Encoding.UTF8));
		});

		// 2) Find enums with [GenerateEnumToString].
		var enums = context.SyntaxProvider.ForAttributeWithMetadataName(
				ATTRIBUTE_FULL_NAME,
				static (node, _) => node is EnumDeclarationSyntax,
				static (ctx, _) => CreateEnumModel(ctx))
			.Where(static m => m is not null)!;

		// 3) Generate source per enum.
		context.RegisterSourceOutput(enums, static (spc, model) =>
		{
			string src = Render(model!);
			spc.AddSource($"{model!.HintName}.EnumToString.g.cs", SourceText.From(src, Encoding.UTF8));
		});
	}

	private static EnumModel? CreateEnumModel(GeneratorAttributeSyntaxContext ctx)
	{
		if (ctx.TargetSymbol is not INamedTypeSymbol enumSymbol || enumSymbol.TypeKind != TypeKind.Enum)
			return null;

		// Only constants that are actual enum members (skip value__).
		var members = enumSymbol.GetMembers()
			.OfType<IFieldSymbol>()
			.Where(f => f.HasConstantValue && f.Name != "value__")
			.Select(f => new EnumMember(f.Name, Convert.ToInt64(f.ConstantValue!)))
			.ToImmutableArray();

		// If there's nothing to generate, bail.
		if (members.Length == 0)
			return null;

		string? ns = enumSymbol.ContainingNamespace?.IsGlobalNamespace == true
			? null
			: enumSymbol.ContainingNamespace?.ToDisplayString();

		bool isFlags = enumSymbol.GetAttributes().Any(a =>
			a.AttributeClass?.ToDisplayString() == "System.FlagsAttribute");

		return new EnumModel(
			Namespace: ns,
			EnumName: enumSymbol.Name,
			EnumFullType: enumSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
			IsFlags: isFlags,
			Accessibility: enumSymbol.DeclaredAccessibility,
			Members: members,
			HintName: MakeHintName(enumSymbol));
	}

	private static string Render(EnumModel model)
	{
		var sb = new StringBuilder(5000);
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");

		if (model.Namespace is not null)
		{
			sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
			sb.AppendLine();
		}

		// Match enum accessibility (public/internal). You can expand if you care about others.
		string access = model.Accessibility switch
		{
			Accessibility.Public => "public",
			_ => "internal"
		};

		sb.Append(access).Append(" static class ").Append(model.EnumName).AppendLine("EnumToStringExtensions");
		sb.AppendLine("{");

		// TryGetName
		sb.AppendLine("    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
		sb.Append("    ").Append(access).Append(" static bool TryGetName(this ").Append(model.EnumFullType).AppendLine(" value, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out string? name)");
		sb.AppendLine("    {");
		sb.AppendLine("        switch (value)");
		sb.AppendLine("        {");

		int totalLength = 0;
		// De-dupe by numeric value (aliases). Pick the first name encountered.
		HashSet<long> seen = [];
		foreach (var m in model.Members)
		{
			totalLength += m.Name.Length;
			if (!seen.Add(m.Value))
				continue;
			
			sb.Append("            case ").Append(model.EnumFullType).Append('.').Append(m.Name)
			  .Append(": name = \"").Append(m.Name).AppendLine("\"; return true;");
		}

		sb.AppendLine("            default: name = null; return false;");
		sb.AppendLine("        }");
		sb.AppendLine("    }");
		sb.AppendLine();

		// Constant
		totalLength += (Math.Max(0, model.Members.Length - 1)) * 2; // for ", "
		sb.Append("    private const int MAX_LENGTH = ").Append(totalLength).AppendLine(";");
		sb.AppendLine();
		sb.AppendLine("    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
		sb.AppendLine("    public static int GetMaxToStringFastLength() => MAX_LENGTH;");
		sb.AppendLine();

		// ToStringFast
		sb.AppendLine("    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
		sb.Append("    ").Append(access).Append(" static string ToStringFast(this ").Append(model.EnumFullType).AppendLine(" value)");
		sb.AppendLine("        => value.TryGetName(out var name) ? name! : value.ToString();");

		sb.AppendLine("}");

		return sb.ToString();
	}

	private static string MakeHintName(INamedTypeSymbol enumSymbol)
	{
		// Unique, stable-ish hint name.
		string fq = enumSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		return fq.Replace("global::", "")
				 .Replace('<', '_')
				 .Replace('>', '_')
				 .Replace('.', '_')
				 .Replace('+', '_');
	}

	private const string ATTRIBUTE_SOURCE = """
// <auto-generated/>
#nullable enable
namespace AD.Api.Generators
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Enum, AllowMultiple = false, Inherited = false)]
	public sealed class GenerateEnumToStringAttribute : global::System.Attribute
	{
	}
}
""";

	private sealed record EnumModel(
		string? Namespace,
		string EnumName,
		string EnumFullType,
		bool IsFlags,
		Accessibility Accessibility,
		ImmutableArray<EnumMember> Members,
		string HintName);

	private sealed record EnumMember(string Name, long Value);
}
