<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AD.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
	<Using Include="AD.Api.Buffers" />
	<Using Include="Microsoft.AspNetCore.Http" />
	<Using Include="Microsoft.Extensions.Configuration" />
	<Using Include="Microsoft.Extensions.DependencyInjection" />
	<Using Include="Microsoft.Extensions.Options" />
	<Using Include="System.Buffers" />
	<Using Include="System.ComponentModel.DataAnnotations" />
	<Using Include="System.Diagnostics" />
	<Using Include="System.Diagnostics.CodeAnalysis" />
	<Using Include="System.DirectoryServices" />
	<Using Include="System.DirectoryServices.Protocols" />
	<Using Include="System.Reflection" />
	<Using Include="System.Runtime.CompilerServices" />
	<Using Include="System.Runtime.InteropServices" />
	<Using Include="System.Text.Json" />
	<Using Include="System.Text.Json.Serialization" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AD.Api.Core\AD.Api.Core.csproj" />
  </ItemGroup>

</Project>
