<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AD.Api</RootNamespace>
	<DebugType>full</DebugType>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

	<ItemGroup Condition=" '$(Configuration)' == 'Debug' ">
		<Content Update="appsettings.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Content>
		<Content Update="appsettings.Development.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup Condition=" '$(Configuration)' == 'Release' ">
		<Content Update="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</Content>
		<Content Update="appsettings.Development.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="AD.Api.Assemblies.DependencyAssemblyAttribute" />
	</ItemGroup>

  <ItemGroup>
	<Using Include="Microsoft.AspNetCore.Mvc" />
	<Using Include="Microsoft.Extensions.Configuration" />
	<Using Include="Microsoft.Extensions.DependencyInjection" />
	<Using Include="System.Buffers" />
	<Using Include="System.Collections" />
	<Using Include="System.ComponentModel" />
	<Using Include="System.Diagnostics" />
	<Using Include="System.Diagnostics.CodeAnalysis" />
	<Using Include="System.DirectoryServices.Protocols" />
	<Using Include="System.Reflection" />
	<Using Include="System.Runtime.CompilerServices" />
	<Using Include="System.Runtime.InteropServices" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <NoWarn>1591;1701;1702</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <NoWarn>1591;1701;1702</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>

	<ItemGroup>
		<Compile Remove="**\Legacy\**\*.cs" />
	</ItemGroup>
	<ItemGroup>
		<None Include="**\Legacy\**\*.cs" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="config.nlog" />
	</ItemGroup>
	<ItemGroup>
	  <Content Include="config.nlog">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
	<ItemGroup>
	  <None Include="Extensions\InjectServicesExtension.cs" />
	  <None Include="Middleware\ErrorHandlingMiddleware.cs" />
	</ItemGroup>

  <!--<ItemGroup>
    <Compile Remove="Middleware\MultipleSchemaAuthenticationMiddleware.cs" />
    <Compile Remove="Services\NewNameService.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Middleware\Legacy\MultipleSchemaAuthenticationMiddleware.cs" />
    <None Include="Services\Legacy\NewNameService.cs" />
  </ItemGroup>-->

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="10.0.1" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.1.1" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AD.Api.Core\AD.Api.Core.csproj" />
    <ProjectReference Include="..\AD.Api.Extensions\AD.Api.Extensions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\Groups\" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>

</Project>
