//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AD.Api.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid domain name or is not configured..
        /// </summary>
        internal static string Error_InvalidDomainName {
            get {
                return ResourceManager.GetString("Error_InvalidDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP://.
        /// </summary>
        internal static string LDAP_Prefix {
            get {
                return ResourceManager.GetString("LDAP_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP://{0}.
        /// </summary>
        internal static string LDAP_PrefixFormat {
            get {
                return ResourceManager.GetString("LDAP_PrefixFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP://RootDSE.
        /// </summary>
        internal static string LDAP_RootDSE {
            get {
                return ResourceManager.GetString("LDAP_RootDSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string LDAPQuery_And {
            get {
                return ResourceManager.GetString("LDAPQuery_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operator.
        /// </summary>
        internal static string LDAPQuery_Operator {
            get {
                return ResourceManager.GetString("LDAPQuery_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string LDAPQuery_Or {
            get {
                return ResourceManager.GetString("LDAPQuery_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objectCategory=person.
        /// </summary>
        internal static string LDAPQuery_User_ObjectCategory {
            get {
                return ResourceManager.GetString("LDAPQuery_User_ObjectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objectClass=user.
        /// </summary>
        internal static string LDAPQuery_User_ObjectClass {
            get {
                return ResourceManager.GetString("LDAPQuery_User_ObjectClass", resourceCulture);
            }
        }
    }
}
