<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
	
	<ItemGroup>
		<AssemblyAttribute Include="AD.Api.Assemblies.DependencyAssemblyAttribute" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="**\*-*.cs">
			<DependentUpon>$([System.Text.RegularExpressions.Regex]::Replace('$([System.String]::Copy(%(Filename)))', '^(.+)\-.+$', '$1.cs'))</DependentUpon>
		</Compile>
	</ItemGroup>
	
	<ItemGroup>
	  <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
	  <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.15.0" />
	  <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.15.0" />
	  <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.0.1" />
	  <PackageReference Include="System.DirectoryServices" Version="10.0.1" />
	  <PackageReference Include="System.DirectoryServices.Protocols" Version="10.0.1" />
	  <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
	  <PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.1" />
		<PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.1" />
	</ItemGroup>
	
	<ItemGroup>
		<Using Include="AD.Api.Resources.ErrorStrings" Alias="Errors" />
		<Using Include="AD.Api.Reflection" />
		<Using Include="Microsoft.AspNetCore.Http" />
		<Using Include="Microsoft.AspNetCore.Mvc" />
		<Using Include="Microsoft.Extensions.Configuration" />
		<Using Include="Microsoft.Extensions.DependencyInjection" />
		<Using Include="Microsoft.Extensions.Options" />
		<Using Include="System.Buffers" />
		<Using Include="System.Collections" />
		<Using Include="System.Diagnostics" />
		<Using Include="System.Diagnostics.CodeAnalysis" />
		<Using Include="System.DirectoryServices.Protocols" />
		<Using Include="System.Reflection" />
		<Using Include="System.Runtime.CompilerServices" />
		<Using Include="System.Runtime.InteropServices" />
		<Using Include="System.Text.Json" />
		<Using Include="System.Text.Json.Serialization" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AD.Api.Extensions\AD.Api.Extensions.csproj" />
  </ItemGroup>
</Project>
